package com.project.credit.bill.controller;

import com.project.credit.bill.entity.Bill;
import com.project.credit.bill.service.BillService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RestController;

@RestController
public class BillController {
    @Autowired
    private BillService billService;
    @GetMapping("/bill")
    public Bill autoGeneratedBillForMonth() {
        return billService.autoGenerateBillForMonth();

    }
    @PostMapping("/bill/{billId}")
    public Boolean billPayment(@PathVariable Long billId){
        return null;
    }

}
