package com.project.credit.bill.controller;

import com.project.credit.bill.entity.Bill;
import com.project.credit.bill.exception.BillException;
import com.project.credit.bill.service.BillService;
import com.project.credit.card.exception.CardException;
import com.project.credit.transaction.exception.DateException;
import com.project.credit.transaction.exception.TransactionException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RestController;

import java.util.List;
@RestController
public class BillController {
    @Autowired
    private BillService billService;

    @GetMapping("/getBill/{cardNumber}")
    public Bill autoGeneratedBillForMonth(@PathVariable String cardNumber) throws TransactionException, BillException, DateException, CardException {
        return billService.autoGenerateBillForMonth(cardNumber);


    }

    @PostMapping("/billPayment/{cardNumber}")
    public Bill billPayment(@PathVariable String cardNumber) throws BillException, CardException, TransactionException {
        return billService.billPayment(cardNumber);
    }

}
